services:
  # API (backend)
  - type: web
    name: goldbroker-kyb-api # replace xxxxx with the customer name
    branch: goldbroker-kyb # replace xxxxx with the customer name
    env: node
    region: frankfurt
    rootDir: backend
    buildCommand: npm run build
    startCommand: npm run prod
    plan: starter
    autoDeploy: true
    buildFilter:
      paths:
        - backend/src
    envVars:
      # Dotfile
      - key: DOTFILE_BASE_URL
        value: https://api.dotfile.com/v1
      - key: DOTFILE_KEY
        sync: false
      - key: TEMPLATE_ID
        sync: false
      - key: WEBHOOK_SECRET
        value: dotsecret.YMq733Tt9rQky6Em6pVK5woMxxHRUdRm # generate a token to replace xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (https://it-tools.tech/token-generator?length=32)
      # Email
      - key: SMTP_HOST
        value: smtp.postmarkapp.com
      - key: SMTP_PORT
        value: 587
      - key: EMAIL_FROM
        value: noreply-goldbroker-kyb@dotfile.com # replace xxxxx with the customer name
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      # Other
      - key: LOGO_URL
        sync: false
      - key: APP_URL
        fromService:
          type: web
          name: goldbroker-kyb-app # replace xxxxx with the customer name
          envVarKey: CUSTOM_DOMAIN # APP (frontend) url
  # APP (frontend)
  - type: web
    name: goldbroker-kyb-app # replace xxxxx with the customer name
    branch: goldbroker-kyb # replace xxxxx with the customer name
    env: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: build
    autoDeploy: true
    buildFilter:
      paths:
        - frontend/src
    domains:
      - goldbroker-kyb.onboarding.dotfile.com # replace xxxxx with the customer name
    envVars:
      - key: REACT_APP_BASE_URL_API
        fromService:
          type: web
          name: goldbroker-kyb-api # replace xxxxx with the customer name
          envVarKey: RENDER_EXTERNAL_URL # API (backend) url
      - key: REACT_APP_BASE_URL
        value: goldbroker-kyb.onboarding.dotfile.com # replace xxxxx with the customer name
      - key: REACT_APP_ENV
        value: production
